app = "karayel-online-server"
primary_region = "fra"

[build]
  dockerfile = "apps/server/Dockerfile"

[env]
  PORT = "2567"

[[services]]
  internal_port = 2567
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
