import type { TowerDefinition } from "../../common/types.js";
import { attachTowerEngine } from "../../common/engine.js";

const color = 0x22c55e;

export const atakanTowers: TowerDefinition[] = ([
  {
    id: "warrior-1",
    characterId: "warrior",
    name: "Takipçi",
    role: "Hasar ve işaretleme",
    description: "Atakan'ın takım hasarını açan temel kulesi. Dengeli tek hedef hasarı verir ve vurduğu düşmana Takipte işareti koyar. İşaretli düşman yalnızca Atakan'dan değil, takımdaki tüm kulelerden daha fazla hasar alır; bu yüzden erken kurulup dalganın önünü işaretlemesi beklenir. Hava hedeflerini de vurabilir.",
    classType: "damage",
    damageType: "physical",
    hitType: "projectile",
    mechanics: ["mark:tracking", "team-damage-amp", "anti-air-ready"],
    cost: 42,
    upgradeCost: 32,
    range: 112,
    damage: 12,
    fireIntervalMs: 720,
    projectileSpeed: 340,
    aoeRadius: 0,
    slowMs: 0,
    color
  },
  {
    id: "warrior-2",
    characterId: "warrior",
    name: "Sunucu",
    role: "Global destek",
    description: "Kendisi hedef seçip ateş etmez; iki kuleye bağlanır ve o kulelerin menzilinden kaçan düşmanları haritanın her yerinden elektrik topuyla vurur. Menzili global olduğu için hattın dibinde durması gerekmez. Aynı kuleye 5 dalga bağlı kalırsa bağlı kulenin çarpma vuruşlarına ek hasar, 10 dalga bağlı kalırsa her vuruşa hedefin maksimum canının bir yüzdesi kadar ek hasar ekler; yani bağı bozmamak ödüllendirilir. Atakan'ın yalnızlık pasifinden etkilenmez.",
    classType: "hybrid",
    damageType: "electric",
    hitType: "impact",
    mechanics: ["server-link-ready", "electric-burst"],
    cost: 74,
    upgradeCost: 54,
    range: 844,
    damage: 0,
    fireIntervalMs: 980,
    projectileSpeed: 310,
    aoeRadius: 18,
    slowMs: 0,
    color
  },
  {
    id: "warrior-3",
    characterId: "warrior",
    name: "İzolasyon Kulesi",
    role: "Alan kontrolü",
    description: "Hiç hasar vermez, sadece yavaşlatır. Çevresinde başka kule varken hedefleri tek tek yavaşlatır; tamamen yalnız bırakılırsa atışı bırakıp sürekli açık, çok daha güçlü bir yavaşlatma aurasına geçer. Hattın darboğazına tek başına kurulmak için tasarlanmıştır.",
    classType: "control",
    damageType: "none",
    hitType: "aura",
    mechanics: ["slow", "solo-aura"],
    cost: 58,
    upgradeCost: 42,
    range: 104,
    damage: 0,
    fireIntervalMs: 620,
    projectileSpeed: 260,
    aoeRadius: 0,
    slowMs: 850,
    color
  },
  {
    id: "warrior-4",
    characterId: "warrior",
    name: "Obsesyon Kulesi",
    role: "Tek hedef hasarı",
    description: "Aynı düşmana üst üste vurdukça her vuruşta hasarını %20 artırır; hedef değiştiğinde birikim sıfırlanır. Bu yüzden hedefini rastgele seçmez, en kalın düşmanı önceliklendirir. Çarpma vuruşlu olduğu için seviye aldıkça atış hızı değil hasarı büyür.",
    classType: "damage",
    damageType: "psychic",
    hitType: "impact",
    mechanics: ["same-target-ramp", "prioritize-tank"],
    cost: 108,
    upgradeCost: 60,
    range: 118,
    damage: 18,
    fireIntervalMs: 760,
    projectileSpeed: 330,
    aoeRadius: 0,
    slowMs: 0,
    color
  },
  {
    id: "warrior-5",
    characterId: "warrior",
    name: "Debug Lazer",
    role: "Sürekli hasar",
    description: "Çok sık ve küçük vuran bir odak lazeri; tek başına zayıf, Takipçi ile birlikte yıkıcıdır. Takipte işaretli düşmanları önceliklendirir. Kesintisiz ateş ettikçe ısınır: 20 saniyelik pencerede 10 saniyeyi doldurursa 5 saniye aşırı ısınıp susar. Hava hedeflerini vuramaz.",
    classType: "damage",
    damageType: "fire",
    hitType: "focus",
    mechanics: ["laser-channel", "prioritize-tracking", "marked-kill-overdrive-ready", "overheat"],
    cost: 82,
    upgradeCost: 78,
    range: 134,
    damage: 5,
    fireIntervalMs: 160,
    projectileSpeed: 620,
    aoeRadius: 10,
    slowMs: 0,
    color
  },
  {
    id: "warrior-6",
    characterId: "warrior",
    name: "Ucube",
    role: "Geç oyun hasarı",
    description: "Geç oyun yatırımı. Çok pahalıdır ve kurulduğu anda maliyetini karşılamaz. Sahada durduğu sürece tamamlanan her 2 dalgada bir kalıcı olarak gelişir, son bonusunu 16. dalgada açar. Ayrıca aralıksız ateş ettikçe atış hızı stack'i toplar, hedefsiz kalırsa stack sıfırlanır. Erken kurup beslemek gerekir; geç kurmak boşa yatırımdır. Hava hedeflerini vurabilir.",
    classType: "damage",
    damageType: "electric",
    hitType: "impact",
    mechanics: ["wave-growth", "attack-speed-stack", "overheat", "anti-air-ready"],
    cost: 240,
    upgradeCost: 115,
    range: 118,
    damage: 13.5,
    fireIntervalMs: 940,
    projectileSpeed: 370,
    aoeRadius: 0,
    slowMs: 0,
    color
  },
  {
    id: "warrior-7", characterId: "warrior", name: "Cephane Merkezi", role: "Mühimmat ikmali",
    description: "Taşınan enerji ve cephane hammaddesini tüketerek mühimmat üretir; lojistik işçisi ürünü sevkiyatı açık kulelere taşır.", classType: "support", damageType: "none", hitType: "aura",
    mechanics: ["resource-supply", "ammunition"], cost: 95, upgradeCost: 60, range: 0, damage: 0, fireIntervalMs: 999999,
    projectileSpeed: 0, aoeRadius: 0, slowMs: 0, color: 0xf59e0b, resourceProvider: "ammunition"
  },
  {
    id: "warrior-8", characterId: "warrior", name: "Enerji Reaktörü", role: "Enerji ikmali",
    description: "Kristal işçilerinin getirdiği kristalleri enerji olarak depolar; enerji işçisi bu enerjiyi kulelere taşır.", classType: "support", damageType: "none", hitType: "aura",
    mechanics: ["resource-supply", "energy"], cost: 105, upgradeCost: 65, range: 0, damage: 0, fireIntervalMs: 999999,
    projectileSpeed: 0, aoeRadius: 0, slowMs: 0, color: 0x22d3ee, resourceProvider: "energy"
  }
] satisfies Array<Omit<TowerDefinition, "engine">>).map(attachTowerEngine);
