import type { TowerDefinition } from "../../common/types.js";

const color = 0x22c55e;

export const atakanTowers: TowerDefinition[] = [
  {
    id: "warrior-1",
    characterId: "warrior",
    name: "Takipci",
    role: "Hasar, isaretleme",
    description: "Dengeli tek hedef hasari verir. Vurdugu dusmana Takipte isareti koyar; isaretli dusmanlar tum kulelerden daha fazla hasar alir.",
    classType: "damage",
    damageType: "physical",
    hitType: "projectile",
    mechanics: ["mark:tracking", "team-damage-amp", "anti-air-ready"],
    cost: 42,
    upgradeCost: 32,
    range: 112,
    damage: 12,
    fireIntervalMs: 720,
    projectileSpeed: 340,
    aoeRadius: 0,
    slowMs: 0,
    color
  },
  {
    id: "warrior-2",
    characterId: "warrior",
    name: "Sunucu",
    role: "Global destek",
    description: "Iki kuleye baglanir. Bagli kulelerin menzilinden cikan dusmanlara global olarak guclu elektrik topu gonderir.",
    classType: "hybrid",
    damageType: "electric",
    hitType: "impact",
    mechanics: ["server-link-ready", "electric-burst"],
    cost: 74,
    upgradeCost: 54,
    range: 844,
    damage: 0,
    fireIntervalMs: 980,
    projectileSpeed: 310,
    aoeRadius: 18,
    slowMs: 0,
    color
  },
  {
    id: "warrior-3",
    characterId: "warrior",
    name: "Izolasyon Kulesi",
    role: "Alan kontrolu",
    description: "Hasar vermez, dusmanlari yavaslatir. Etrafinda baska kule yoksa atis yerine daha guclu yavaslatma aurasi acar.",
    classType: "control",
    damageType: "none",
    hitType: "aura",
    mechanics: ["slow", "solo-aura"],
    cost: 58,
    upgradeCost: 42,
    range: 104,
    damage: 0,
    fireIntervalMs: 620,
    projectileSpeed: 260,
    aoeRadius: 0,
    slowMs: 850,
    color
  },
  {
    id: "warrior-4",
    characterId: "warrior",
    name: "Obsesyon Kulesi",
    role: "Hasar",
    description: "Ayni dusmana vurdukca sonraki vurusunu yuzde 20 guclendirir. Tank dusmanlari onceliklendirir.",
    classType: "damage",
    damageType: "psychic",
    hitType: "impact",
    mechanics: ["same-target-ramp", "prioritize-tank"],
    cost: 108,
    upgradeCost: 60,
    range: 118,
    damage: 18,
    fireIntervalMs: 760,
    projectileSpeed: 330,
    aoeRadius: 0,
    slowMs: 0,
    color
  },
  {
    id: "warrior-5",
    characterId: "warrior",
    name: "Debug Lazer",
    role: "Hasar, AOE",
    description: "Takipte dusmanlara oncelik veren odak lazeri. Cok sik kucuk hasar vurur ve isaretli hedefleri eritmek icin tasarlandi.",
    classType: "damage",
    damageType: "fire",
    hitType: "focus",
    mechanics: ["laser-channel", "prioritize-tracking", "marked-kill-overdrive-ready"],
    cost: 82,
    upgradeCost: 78,
    range: 134,
    damage: 5,
    fireIntervalMs: 160,
    projectileSpeed: 620,
    aoeRadius: 10,
    slowMs: 0,
    color
  },
  {
    id: "warrior-6",
    characterId: "warrior",
    name: "Ucube",
    role: "Gec oyun hasari",
    description: "Cok pahali ve zayif baslar. Sahadayken tamamlanan dalgalarla 2 dalgada bir otomatik gelisir; son bonusu 16. dalgada acilir. Araliksiz calistikca saldiri hizi stack kazanir, bos kalirsa sifirlanir, erken oyunda hararet yapabilir.",
    classType: "damage",
    damageType: "electric",
    hitType: "impact",
    mechanics: ["wave-growth", "attack-speed-stack", "overheat", "anti-air-ready"],
    cost: 240,
    upgradeCost: 115,
    range: 118,
    damage: 9,
    fireIntervalMs: 940,
    projectileSpeed: 370,
    aoeRadius: 0,
    slowMs: 0,
    color
  }
];
