import type { TowerDefinition } from "../../common/types.js";
import { attachTowerEngine } from "../../common/engine.js";

export const melisTowers: TowerDefinition[] = ([
  {
    id: "archer-1",
    characterId: "archer",
    name: "Hedefçi",
    role: "Kilitlenen tek hedef",
    description: "Menziline giren bir hedefe kilitlenir ve onu bırakmaz. Onay baskınken hedef menzilden çıksa bile takibi sürer; denge veya stres durumunda menzilden çıkan hedefin kilidi kopar. Aynı hedefe kilitlenen Hedefçi sayısı arttıkça hasarları birlikte büyür, bu yüzden ikili üçlü kurulur.",
    classType: "damage",
    damageType: "psychic",
    hitType: "projectile",
    cost: 76,
    upgradeCost: 55,
    range: 79,
    damage: 32,
    fireIntervalMs: 820,
    projectileSpeed: 520,
    aoeRadius: 0,
    slowMs: 0,
    color: 0x8b5cf6
  },
  {
    id: "archer-2",
    characterId: "archer",
    name: "Parlama",
    role: "Öfke patlaması",
    description: "Hedeflediği düşmanı menzilinden çıkana kadar öldüremezse öfkelenir ve çevresine iki katı alan hasarı ile yarım saniyelik korku dalgası salar. Yani öldüremediği her hedef bir patlamaya dönüşür. Stres baskınken bu patlama kendi alanındaki dost kuleleri de yarım saniye durdurur; güçlüdür ama kontrolsüzdür.",
    classType: "damage",
    damageType: "psychic",
    hitType: "projectile",
    cost: 92,
    upgradeCost: 67,
    range: 74,
    damage: 22,
    fireIntervalMs: 950,
    projectileSpeed: 460,
    aoeRadius: 0,
    slowMs: 0,
    color: 0xdb2777
  },
  {
    id: "archer-3",
    characterId: "archer",
    name: "Lanet Kulesi",
    role: "Biriken lanet yükü",
    description: "Alanındaki düşmanlara lanet yükler. Lanet doğrudan hasar vermez, sınırsız birikir; lanetli düşman öldüğünde biriktirdiği yük kadar çevresine psişik hasar patlatır. Yani asıl hasarı öldüren kule değil, ölen düşman verir. Kalabalık dalgalarda zincirleme patlama kurmak için kullanılır.",
    classType: "damage",
    damageType: "psychic",
    hitType: "curse",
    cost: 109,
    upgradeCost: 74,
    range: 73,
    damage: 15,
    fireIntervalMs: 1180,
    projectileSpeed: 0,
    aoeRadius: 42,
    slowMs: 0,
    color: 0x7f1dff
  },
  {
    id: "archer-4",
    characterId: "archer",
    name: "Ölüler Bağı",
    role: "Execute ve ruh bağı",
    description: "Bir düşmana bağlanır ve o düşman ölene ya da nexusa ulaşana kadar bağını sürdürür. Hedefin canı execute eşiğinin altına indiğinde onu doğrudan ölüler alemine çeker; kalan canı ne olursa olsun düşman ölür. Bağ uzadıkça eşik yükselir, yani hedefi ne kadar uzun tutarsa o kadar erken infaz eder. Çektiği her düşman moduna göre Melis'e onay veya stres kazandırır.",
    classType: "control",
    damageType: "psychic",
    hitType: "focus",
    cost: 113,
    upgradeCost: 76,
    range: 78,
    damage: 0,
    fireIntervalMs: 1350,
    projectileSpeed: 0,
    aoeRadius: 0,
    slowMs: 0,
    color: 0x14b8a6
  },
  {
    id: "archer-5",
    characterId: "archer",
    name: "Kırık Ayna",
    role: "Gecikmeli patlama",
    description: "Kendisi neredeyse hiç hasar vermez; komşu 8 karedeki Melis kulelerinin verdiği hasarın bir kısmını içinde biriktirir. Deposu dolduğunda biriken hasarı seviyesine göre 1.10 ile 2.00 kat arasında bir çarpanla tek seferde patlatır. Yani çevresindeki kuleler ne kadar güçlüyse patlaması o kadar büyür. Hedefi ruh haline göre seçer: onayda çıkışa en yakın, dengede canı en yüksek, streste rastgele düşman.",
    classType: "hybrid",
    damageType: "psychic",
    hitType: "impact",
    cost: 139,
    upgradeCost: 88,
    range: 120,
    damage: 10,
    fireIntervalMs: 1750,
    projectileSpeed: 360,
    aoeRadius: 0,
    slowMs: 0,
    color: 0xe879f9
  },
  {
    id: "archer-6",
    characterId: "archer",
    name: "Fısıltı Korosu",
    role: "Alan kontrolü ve şüphe",
    description: "Düşmanın karar verme mekanizmasını bozan bir dalga yayar. Vurduğu her düşmana Şüphe yükler; her yük %10 yavaşlatma uygular ve yeterince şüphe biriken düşman kısa süre duraksayıp hiç ilerlemez. Hasar kulesi değildir, dalgayı yerinde tutmak için kurulur.",
    classType: "control",
    damageType: "psychic",
    hitType: "wave",
    cost: 113,
    upgradeCost: 76,
    range: 78,
    damage: 5,
    fireIntervalMs: 1350,
    projectileSpeed: 0,
    aoeRadius: 40,
    slowMs: 0,
    color: 0x14b8a6
  },
  {
    id: "archer-7", characterId: "archer", name: "Gölge Cephaneliği", role: "Mühimmat ikmali",
    description: "Taşınan enerji ve cephane hammaddesini tüketerek mühimmat üretir; lojistik işçisi ürünü sevkiyatı açık kulelere taşır.", classType: "support", damageType: "none", hitType: "aura",
    cost: 95, upgradeCost: 60, range: 0, damage: 0, fireIntervalMs: 999999,
    projectileSpeed: 0, aoeRadius: 0, slowMs: 0, color: 0xf59e0b, resourceProvider: "ammunition"
  },
  {
    id: "archer-8", characterId: "archer", name: "Ruh Reaktörü", role: "Enerji ikmali",
    description: "Kristal işçilerinin getirdiği kristalleri enerji olarak depolar; enerji işçisi bu enerjiyi kulelere taşır.", classType: "support", damageType: "none", hitType: "aura",
    cost: 105, upgradeCost: 65, range: 0, damage: 0, fireIntervalMs: 999999,
    projectileSpeed: 0, aoeRadius: 0, slowMs: 0, color: 0x22d3ee, resourceProvider: "energy"
  }
] satisfies Array<Omit<TowerDefinition, "engine">>).map(attachTowerEngine);
