import type { TowerDefinition } from "../../common/types.js";

export const melisTowers: TowerDefinition[] = [
  {
    id: "archer-1",
    characterId: "archer",
    name: "Hedefci",
    role: "Menzilli takinti",
    description: "Bir hedef belirler ve hedef olene kadar ona odaklanir. Stres baskinken menzil siniri kalkar. Onayla favori kule olarak cok verimli hale gelir.",
    classType: "damage",
    damageType: "psychic",
    hitType: "projectile",
    mechanics: ["focus-lock", "stress-global-range", "favorite-approval-scaling"],
    cost: 72,
    upgradeCost: 52,
    range: 63,
    damage: 16,
    fireIntervalMs: 820,
    projectileSpeed: 520,
    aoeRadius: 0,
    slowMs: 0,
    color: 0x8b5cf6
  },
  {
    id: "archer-2",
    characterId: "archer",
    name: "Parlama",
    role: "Ofke patlamasi",
    description: "Hedefledigi dusmani menzilinden cikana kadar olduremezse ofke dalgasi salar ve temas edenlere korku uygular. Stres baskinken kendi alanindaki dost kuleleri 0.5 saniye durdurur.",
    classType: "damage",
    damageType: "psychic",
    hitType: "projectile",
    mechanics: ["rage-wave-on-escape", "fear", "stress-friendly-pause"],
    cost: 88,
    upgradeCost: 64,
    range: 59,
    damage: 22,
    fireIntervalMs: 950,
    projectileSpeed: 460,
    aoeRadius: 0,
    slowMs: 0,
    color: 0xdb2777
  },
  {
    id: "archer-3",
    characterId: "archer",
    name: "Lanet Kulesi",
    role: "Biriken lanet yukleri",
    description: "Bir alandaki dusmanlari lanetler. Lanet sonsuz birikir; lanetli dusman oldugunde biriken yuk kadar cevresine psisik hasar verir. Normal sure 5sn, stres baskinken 3sn ve daha genis alan, onay baskinken 7sn.",
    classType: "damage",
    damageType: "psychic",
    hitType: "curse",
    mechanics: ["stacking-curse", "death-burst", "approval-duration", "stress-area"],
    cost: 104,
    upgradeCost: 70,
    range: 58,
    damage: 15,
    fireIntervalMs: 1180,
    projectileSpeed: 0,
    aoeRadius: 42,
    slowMs: 0,
    color: 0x7f1dff
  },
  {
    id: "archer-4",
    characterId: "archer",
    name: "Ölüler Bağı",
    role: "Execute ve ruh bağı",
    description: "Bir dusmana baglanir ve hedef olene ya da nexusa ulasana kadar bagini surdurur. Hedefin cani execute esiginin altina indiginde onu oluler alemine ceker. Onay modunda cekilen dusman +1 onay, stres modunda +1 stres verir. Bag uzadikca execute esigi duser; kule seviye aldikca esik yukselir ve sindirim suresi kisalir.",
    classType: "control",
    damageType: "psychic",
    hitType: "focus",
    mechanics: ["bind-until-death", "execute-threshold", "approval-stress-mode", "digest-cooldown", "underworld-pull-scaling"],
    cost: 108,
    upgradeCost: 72,
    range: 62,
    damage: 0,
    fireIntervalMs: 1350,
    projectileSpeed: 0,
    aoeRadius: 0,
    slowMs: 0,
    color: 0x14b8a6
  },
  {
    id: "archer-5",
    characterId: "archer",
    name: "Kırık Ayna",
    role: "Gecikmeli patlama",
    description: "Yakinindaki Melis kulelerinin verdigi gercek hasarin bir kismini icinde depolar. Deposu dolunca spektrum durumuna gore bir hedef secip birikmis psisik hasari patlatir. Onay baskinken cikisa en yakin hedefe, dengedeyken can yuzdesi en yuksek hedefe, stres baskinken rastgele hedefe patlar.",
    classType: "hybrid",
    damageType: "psychic",
    hitType: "impact",
    mechanics: ["damage-storage", "delayed-burst", "approval-exit-target", "stress-random-target", "evolution-true-damage"],
    cost: 132,
    upgradeCost: 84,
    range: 64,
    damage: 10,
    fireIntervalMs: 1750,
    projectileSpeed: 360,
    aoeRadius: 0,
    slowMs: 0,
    color: 0xe879f9
  },
  {
    id: "archer-6",
    characterId: "archer",
    name: "Fısıltı Korosu",
    role: "Alan kontrolu ve suphe",
    description: "Dusmanlarin karar verme mekanizmasini bozan gotik bir dalga yayar. Vurdugu dusmanlara Suphe stack'i uygular; yeterince suphe biriken dusmanlar kisa sure duraksar. Onay baskinken suphe daha uzun surer, stres baskinken daha az stack ile tetiklenir ama dusman sonra kisa sure hizlanir.",
    classType: "control",
    damageType: "psychic",
    hitType: "wave",
    mechanics: ["doubt-stacks", "hesitation", "approval-duration", "stress-threshold"],
    cost: 108,
    upgradeCost: 72,
    range: 62,
    damage: 5,
    fireIntervalMs: 1350,
    projectileSpeed: 0,
    aoeRadius: 40,
    slowMs: 0,
    color: 0x14b8a6
  }
];
