import type { TowerDefinition } from "../../common/types.js";

export const melisTowers: TowerDefinition[] = [
  {
    id: "archer-1",
    characterId: "archer",
    name: "Hedefci",
    role: "Menzilli takinti",
    description: "Menziline giren bir hedefe kilitlenir. Onay baskinken hedef menzil disina ciksa bile ona odaklanir; stres veya denge durumunda hedef menzilden cikarsa kilit kopar. Evrimlerle Oluler Bagi hedeflerine oncelik verir, ayni hedefe vuran Hedefcilerle hasari artar ve Suphe yuklerinden hedefe ozel atis hizi kazanir.",
    classType: "damage",
    damageType: "psychic",
    hitType: "projectile",
    mechanics: ["focus-lock", "underworld-priority", "shared-focus-damage", "doubt-fire-rate"],
    cost: 72,
    upgradeCost: 52,
    range: 79,
    damage: 16,
    fireIntervalMs: 820,
    projectileSpeed: 520,
    aoeRadius: 0,
    slowMs: 0,
    color: 0x8b5cf6
  },
  {
    id: "archer-2",
    characterId: "archer",
    name: "Parlama",
    role: "Ofke patlamasi",
    description: "Hedefledigi dusmani menzilinden cikana kadar olduremezse 0.5 saniyelik korku dalgasi salar. Evrimlerle son vurus dalgasi, kalkanlara 2x dalga hasari ve +0.5 saniye korku suresi kazanir. Stres baskinken kendi alanindaki dost kuleleri 0.5 saniye durdurur.",
    classType: "damage",
    damageType: "psychic",
    hitType: "projectile",
    mechanics: ["rage-wave-on-escape", "kill-trigger-rage", "shield-break-wave", "fear", "stress-friendly-pause"],
    cost: 88,
    upgradeCost: 64,
    range: 74,
    damage: 22,
    fireIntervalMs: 950,
    projectileSpeed: 460,
    aoeRadius: 0,
    slowMs: 0,
    color: 0xdb2777
  },
  {
    id: "archer-3",
    characterId: "archer",
    name: "Lanet Kulesi",
    role: "Biriken lanet yukleri",
    description: "Bir alandaki dusmanlari lanetler. Lanet sonsuz birikir; lanetli dusman oldugunde biriken yuk kadar cevresine psisik hasar verir. Evrimlerle lanet alani genisler, olen hedefin altinda lanet goleti kalir ve son evrimde golet 0.5 saniyede bir lanet uygular.",
    classType: "damage",
    damageType: "psychic",
    hitType: "curse",
    mechanics: ["stacking-curse", "death-burst", "curse-pool", "approval-duration", "stress-area"],
    cost: 104,
    upgradeCost: 70,
    range: 73,
    damage: 15,
    fireIntervalMs: 1180,
    projectileSpeed: 0,
    aoeRadius: 42,
    slowMs: 0,
    color: 0x7f1dff
  },
  {
    id: "archer-4",
    characterId: "archer",
    name: "Ölüler Bağı",
    role: "Execute ve ruh bağı",
    description: "Bir dusmana baglanir ve hedef olene ya da nexusa ulasana kadar bagini surdurur. Hedefin cani execute esiginin altina indiginde onu oluler alemine ceker. Onay modunda cekilen dusman +1 onay, stres modunda +1 stres verir. Bag uzadikca execute esigi duser; kule seviye aldikca esik yukselir ve sindirim suresi kisalir.",
    classType: "control",
    damageType: "psychic",
    hitType: "focus",
    mechanics: ["bind-until-death", "execute-threshold", "approval-stress-mode", "digest-cooldown", "underworld-pull-scaling"],
    cost: 108,
    upgradeCost: 72,
    range: 78,
    damage: 0,
    fireIntervalMs: 1350,
    projectileSpeed: 0,
    aoeRadius: 0,
    slowMs: 0,
    color: 0x14b8a6
  },
  {
    id: "archer-5",
    characterId: "archer",
    name: "Kırık Ayna",
    role: "Gecikmeli patlama",
    description: "Komsu 8 karedeki Melis kulelerinin verdigi gercek hasarin bir kismini icinde depolar. Deposu dolunca depoladigi hasari leveline gore %10-%50 artirarak patlatir. Onay baskinken cikisa en yakin hedefe, dengedeyken can yuzdesi en yuksek hedefe, stres baskinken rastgele hedefe patlar.",
    classType: "hybrid",
    damageType: "psychic",
    hitType: "impact",
    mechanics: ["damage-storage", "delayed-burst", "approval-exit-target", "stress-random-target", "evolution-true-damage"],
    cost: 132,
    upgradeCost: 84,
    range: 120,
    damage: 10,
    fireIntervalMs: 1750,
    projectileSpeed: 360,
    aoeRadius: 0,
    slowMs: 0,
    color: 0xe879f9
  },
  {
    id: "archer-6",
    characterId: "archer",
    name: "Fısıltı Korosu",
    role: "Alan kontrolu ve suphe",
    description: "Dusmanlarin karar verme mekanizmasini bozan gotik bir dalga yayar. Suphe stack'i ve stack basina %10 yavaslatma uygular; yeterince suphe biriken dusman kisa sure duraksar. Evrimliyken korku altindaki dusmanda duraksama tetiklenirse dusman 1 saniyeligine taraf degistirir.",
    classType: "control",
    damageType: "psychic",
    hitType: "wave",
    mechanics: ["doubt-stacks", "stacking-slow", "hesitation", "fear-conversion", "temporary-turncoat", "suicide-burst"],
    cost: 108,
    upgradeCost: 72,
    range: 78,
    damage: 5,
    fireIntervalMs: 1350,
    projectileSpeed: 0,
    aoeRadius: 40,
    slowMs: 0,
    color: 0x14b8a6
  }
];
