create table if not exists public.match_telemetry (
  id bigint generated by default as identity primary key,
  room_id text not null,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  outcome text not null check (outcome in ('defeat', 'abandoned')),
  wave integer not null check (wave >= 1),
  kills integer not null check (kills >= 0),
  team_health numeric not null,
  map_scale text not null,
  players jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists match_telemetry_ended_at_idx
  on public.match_telemetry (ended_at desc);

alter table public.match_telemetry enable row level security;
